"""
Django settings for ticket_booking_system project.

Generated by 'django-admin startproject' using Django 5.2.7.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING：生产环境请通过环境变量读取
SECRET_KEY = 'django-insecure-=bmd+_pf!+un%8(wel+$(b+pwj#3zh7t4ee*x+1dpcg#mr-t7p'

DEBUG = True
ALLOWED_HOSTS = []

# -------------------- 应用 --------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'flights',
    'bookings',
    'pages',
    'django_extensions'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ticket_booking_system.urls'

# -------------------- 模板 --------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # 全局模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ticket_booking_system.wsgi.application'

# -------------------- 数据库 --------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------- 国际化 --------------------
LANGUAGE_CODE = 'zh-hans'      # 中文
TIME_ZONE = 'Asia/Shanghai'    # 本地时区
USE_I18N = True
USE_TZ = True

# -------------------- 静态文件 --------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # 开发阶段额外静态目录

# -------------------- 其他 --------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

