# Generated by Django 5.2.7 on 2025-11-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'permissions': [('can_view_flight', 'Can view flight'), ('can_add_flight', 'Can add flight'), ('can_change_flight', 'Can change flight'), ('can_delete_flight', 'Can delete flight')]},
        ),
    ]
